version: 2

jobs:
  deploy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: Deploy infrastructure
          command: |
            chmod u+x ci/scripts/deploy.sh
            ls -l ci/scripts/deploy.sh
            ci/scripts/deploy.sh | sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
